// capture.c - clocked whole-track capture: PIO samples READ DATA on READ/REF
// CLOCK, DMA streams it to SRAM. Runs on core1 (CORE-4) so the host link and
// register bus on core0 are never starved.

#include "capture.h"
#include "board_pins.h"

#include "pico/stdlib.h"
#include "pico/multicore.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/gpio.h"

#include "capture.pio.h"   // generated by pico_generate_pio_header()

// The PIO `wait gpio` clock pin must match the board map.
_Static_assert(capture_CAPTURE_CLK_GPIO == PIN_READ_REF_CLK,
               "capture.pio CAPTURE_CLK_GPIO must equal PIN_READ_REF_CLK");

// Whole-track buffer in core-shared SRAM (CORE-3). ~15 KB; 520 KB SRAM leaves
// room for 30+ tracks if we later double-buffer / batch.
static uint32_t s_track_buf[CAPTURE_WORDS];

static PIO  s_pio;
static uint s_sm;
static uint s_offset;
static int  s_dma_chan;

// Max time to wait for the once-per-rev INDEX edge (rev is ~16.67 ms).
#define INDEX_TIMEOUT_US  60000u

// Max wait for the track DMA. A full track at 6.4 Mbit/s is ~19 ms; if the
// READ/REF CLOCK stalls or never appears (VFO unlocked, cabling), the PIO
// stops pushing and the DMA would otherwise hang core1 (and with it the
// console) forever, with the drive still spinning.
#define DMA_TIMEOUT_MS    250u

static void capture_init(void) {
    // pio1, not pio0: cyw43_arch_init() (LED heartbeat) claims its SPI SM from
    // pio0 at boot; a separate block keeps the two programs out of the same
    // 32-slot instruction memory (CORE-5 "separate blocks").
    s_pio = pio1;
    s_sm  = (uint)pio_claim_unused_sm(s_pio, true);
    s_offset = (uint)pio_add_program(s_pio, &capture_program);

    pio_sm_config c = capture_program_get_default_config(s_offset);
    sm_config_set_in_pins(&c, PIN_READ_DATA);                 // `in pins,1` source
    sm_config_set_in_shift(&c, /*shift_right=*/true,
                               /*autopush=*/true, /*push_threshold=*/32);
    sm_config_set_clkdiv(&c, 1.0f);                           // follow external clock

    // Route the two input pins to the PIO; both are inputs.
    pio_gpio_init(s_pio, PIN_READ_DATA);
    pio_gpio_init(s_pio, PIN_READ_REF_CLK);
    pio_sm_set_consecutive_pindirs(s_pio, s_sm, PIN_READ_DATA, 1, false);
    pio_sm_set_consecutive_pindirs(s_pio, s_sm, PIN_READ_REF_CLK, 1, false);

    pio_sm_init(s_pio, s_sm, s_offset, &c);   // leave disabled; armed per-track

    // DMA: PIO RX FIFO -> track buffer, paced by the RX DREQ.
    s_dma_chan = dma_claim_unused_channel(true);
    dma_channel_config dc = dma_channel_get_default_config(s_dma_chan);
    channel_config_set_transfer_data_size(&dc, DMA_SIZE_32);
    channel_config_set_read_increment(&dc, false);            // fixed FIFO address
    channel_config_set_write_increment(&dc, true);            // walk the buffer
    channel_config_set_dreq(&dc, pio_get_dreq(s_pio, s_sm, false /*rx*/));
    dma_channel_configure(s_dma_chan, &dc,
                          s_track_buf, &s_pio->rxf[s_sm], CAPTURE_WORDS, false);

    // INDEX as a plain input (active-high at the core via U3).
    gpio_init(PIN_INDEX);
    gpio_set_dir(PIN_INDEX, GPIO_IN);
}

// Wait for a rising edge of INDEX (0->1). Returns false on timeout.
static bool wait_index_rising(void) {
    absolute_time_t deadline = make_timeout_time_us(INDEX_TIMEOUT_US);
    while (gpio_get(PIN_INDEX)) {                 // wait for a low (between pulses)
        if (time_reached(deadline)) return false;
    }
    while (!gpio_get(PIN_INDEX)) {                // then the rising edge
        if (time_reached(deadline)) return false;
    }
    return true;
}

// Perform one INDEX-aligned whole-track capture. Returns words captured (==
// CAPTURE_WORDS) or 0 on failure. Head select / -READ GATE / settling are the
// caller's responsibility (done on core0 before requesting GO).
static uint32_t capture_do(void) {
    // Reset SM + FIFOs and point the PC back at the program start.
    pio_sm_set_enabled(s_pio, s_sm, false);
    pio_sm_clear_fifos(s_pio, s_sm);
    pio_sm_restart(s_pio, s_sm);
    pio_sm_exec(s_pio, s_sm, pio_encode_jmp(s_offset));

    // Re-arm DMA at the buffer start.
    dma_channel_set_write_addr(s_dma_chan, s_track_buf, false);
    dma_channel_set_trans_count(s_dma_chan, CAPTURE_WORDS, false);

    // Align the capture window to the start of a revolution (CAP-3).
    if (!wait_index_rising()) return 0;

    // Arm DMA, then enable the SM so sampling begins immediately after INDEX.
    dma_channel_start(s_dma_chan);
    pio_sm_set_enabled(s_pio, s_sm, true);

    // Block until one full track (+margin) has DMA'd in; bounded, so a
    // stalled clock returns a partial count instead of wedging core1.
    absolute_time_t deadline = make_timeout_time_ms(DMA_TIMEOUT_MS);
    while (dma_channel_is_busy(s_dma_chan)) {
        if (time_reached(deadline)) {
            dma_channel_abort(s_dma_chan);
            pio_sm_set_enabled(s_pio, s_sm, false);
            // TRANS_COUNT holds transfers *remaining* after an abort.
            uint32_t remaining = dma_channel_hw_addr(s_dma_chan)->transfer_count;
            return CAPTURE_WORDS - remaining;
        }
    }
    pio_sm_set_enabled(s_pio, s_sm, false);
    return CAPTURE_WORDS;
}

void capture_core_main(void) {
    capture_init();
    multicore_fifo_push_blocking(CAP_MSG_READY);
    for (;;) {
        uint32_t req = multicore_fifo_pop_blocking();
        if (req == CAP_REQ_GO) {
            uint32_t words = capture_do();
            multicore_fifo_push_blocking(words ? words : CAP_RESP_FAIL);
        } else {
            multicore_fifo_push_blocking(CAP_RESP_FAIL);
        }
    }
}

// Launch core1 on first use so the console/bus never block on PIO/DMA bring-up.
static bool s_core1_started = false;

bool capture_ensure_started(void) {
    if (s_core1_started) return false;
    multicore_launch_core1(capture_core_main);
    while (multicore_fifo_pop_blocking() != CAP_MSG_READY) { /* spin */ }
    s_core1_started = true;
    return true;
}

uint32_t capture_run_blocking(void) {
    capture_ensure_started();
    multicore_fifo_push_blocking(CAP_REQ_GO);
    uint32_t r = multicore_fifo_pop_blocking();
    return (r == CAP_RESP_FAIL) ? 0u : r;
}

const uint32_t *capture_buffer(void)              { return s_track_buf; }
uint32_t        capture_buffer_capacity_words(void) { return CAPTURE_WORDS; }
